# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-17 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTestPythoAnyWhere', '0002_myemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyEmail',
        ),
    ]
